#!/local/perl/bin/perl

=head1 NAME

pod2sst -- Convert Perl POD to SST prologue

=head1 SYNOPSIS

  pod2sst file > file.sst

=head1 DESCRIPTION

This program reads in Perl code containing POD and converts that POD
into an SST prologue, which is output to STDOUT.

=head1 OPTIONS

The following options are supported:

=over 4

=item B<-help>

Print help information.

=item B<-version>

Print version information.

=item B<-man>

Print the full documentation to STDOUT.

=back

=cut

use strict;

use Getopt::Long;
use Pod::SST;
use Pod::Usage;
use Starlink::Prologue;

my ( $help, $man, $version );
my $ostatus = GetOptions( "help" => \$help,
                          "man" => \$man,
                          "version" => \$version,
                        );

pod2usage(1) if $help;
pod2usage( -exitstatus => 0, -verbose => 2 ) if $man;
if( $version ) {
  my $id = '$Id: $';
  print "pod2sst - convert Perl POD to Starlink SST\n";
  print " SVN version: $id\n";
  exit;
}

my $inputfile = $ARGV[0];

if( ! defined( $inputfile ) || ! -e $inputfile ) {
  pod2usage(1);
}

my $parser = Pod::SST->new();
$parser->parse_file( $inputfile );

$parser->write_prologue;

=head1 AUTHOR

Brad Cavanagh E<lt>b.cavanagh@jach.hawaii.eduE<gt>

=head1 COPYRIGHT

Copyright (C) 2007 Science and Technology Facilities Council.  All
Rights Reserved.

This program is free software; you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation; either version 2 of the License, or (at
your option) any later version.

This program is distributed in the hope that it will be useful,but
WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program; if not, write to the Free Software
Foundation, Inc., 59 Temple Place,Suite 330, Boston, MA 02111-1307,
USA

=cut
